package com.goldenhour.utils

data class AppStrings(
    val subtitle: String,
    val tagline: String,
    val languagePrompt: String,
    val continueLabel: String,
    val developedBy: String,
    val prototypeNotice: String,
    val simulationBadge: String,
    val stepAlert: String,
    val stepRoute: String,
    val stepHospital: String,
    val sosSimulationNotice: String,
    val triageSimulationNotice: String,
    val simulatedDispatchChecklist: String,
    val academicSafetyNote: String,
    val alertingSafetyNotice: String,
    val dashboardSubtitle: String,
    val greenCorridorActive: String,
    val speed: String,
    val destination: String,
    val minutesUnit: String,
    val speedUnit: String,
    val roadmapDescription: String,
    val liveGpsSimulation: String,
    val ambulanceOnWay: String,
    val paramedicUnit: String,
    val trackingDispatched: String,
    val trackingEnRoute: String,
    val trackingNearScene: String,
    val trackingArriving: String,
    val distanceRemaining: String,
    val lastUpdated: String,
    val simulatedAiTitle: String,
    val activeSimulation: String,
    val offlineComputed: String,
    val severityResult: String,
    val traumaScoreResult: String,
    val allocationReason: String,
    val sceneAnalysisResult: String,
    val protectedTitle: String,
    val protectedDescription: String,
    val treatmentNotice: String,
    val anonymityNotice: String,
    val legalTitle: String,
    val legalBody: String,
    val financialTitle: String,
    val financialBody: String,
    val anonymousTitle: String,
    val anonymousBody: String,
    val faqTitle: String,
    val faqPoliceQuestion: String,
    val faqPoliceAnswer: String,
    val faqProtectedQuestion: String,
    val faqProtectedAnswer: String,
    val faqIdentityQuestion: String,
    val faqIdentityAnswer: String,
    val understandButton: String,
    val gslProtected: String,
    val locationTitle: String,
    val traumaCentreTitle: String,
    val distance: String,
    val eta: String,
    val victimCount: String,
    val tapAlert: String,
    val call108: String,
    val call112: String,
    val triageTitle: String,
    val triageSubtitle: String,
    val questionConscious: String,
    val questionBleeding: String,
    val questionBreathing: String,
    val yes: String,
    val no: String,
    val previous: String,
    val voiceReport: String,
    val tapSpeak: String,
    val simulatedListening: String,
    val describeScene: String,
    val scenePlaceholder: String,
    val skip: String,
    val proceed: String,
    val alertingTitle: String,
    val alertingSubtitle: String,
    val locationPinged: String,
    val traumaIdentified: String,
    val triageSent: String,
    val ambulanceDispatched: String,
    val corridorActivated: String,
    val hospitalAlerted: String,
    val ambulanceEta: String,
    val corridor: String,
    val active: String,
    val liveTracking: String,
    val currentLocation: String,
    val traumaTeamPreparing: String,
    val surgeonAlerted: String,
    val bloodBank: String,
    val emergencyBay: String,
    val radiology: String,
    val theatre: String,
    val triageReceived: String,
    val triageSummary: String,
    val conscious: String,
    val unconscious: String,
    val bleeding: String,
    val noBleeding: String,
    val breathing: String,
    val notBreathing: String,
    val notAnswered: String,
    val roadmapTitle: String,
    val futureFeature: String,
    val aiSeverity: String,
    val aiScoring: String,
    val aiAllocation: String,
    val aiScene: String,
    val restart: String
)

private val English = AppStrings(
    subtitle = "Road Traffic Accident Response",
    tagline = "Every second matters.",
    languagePrompt = "Choose your language",
    continueLabel = "Continue",
    developedBy = "Developed by Aadi Shah (CSE Engineer) and Diksha Mohanty (MBBS Student)",
    prototypeNotice = "Prototype Version 1.0 · Academic Demonstration Only",
    simulationBadge = "SIMULATION",
    stepAlert = "Alert",
    stepRoute = "Route",
    stepHospital = "Hospital",
    sosSimulationNotice = "Simulated alert only — no data is transmitted",
    triageSimulationNotice = "Academic simulation only. No microphone audio or hospital alert is transmitted.",
    simulatedDispatchChecklist = "Simulated dispatch checklist",
    academicSafetyNote = "Academic safety note",
    alertingSafetyNotice = "This app does not contact MGM Hospital, ambulance services, police, or any external backend. All communication shown here is simulated sample data.",
    dashboardSubtitle = "Simulated hospital preparation dashboard",
    greenCorridorActive = "Green corridor active",
    speed = "Speed",
    destination = "Destination",
    minutesUnit = "min",
    speedUnit = "km/h",
    roadmapDescription = "Offline simulated AI modules are active for prototype demonstration. They do not replace clinician judgement.",
    liveGpsSimulation = "LIVE GPS SIMULATION",
    ambulanceOnWay = "Ambulance is on the way",
    paramedicUnit = "Paramedic Unit GH-12",
    trackingDispatched = "Ambulance dispatched",
    trackingEnRoute = "Crossing Kamothe sector roads",
    trackingNearScene = "Near NH-66 Junction",
    trackingArriving = "Arriving at accident site",
    distanceRemaining = "Distance remaining",
    lastUpdated = "Updated just now",
    simulatedAiTitle = "Simulated AI Decision Support",
    activeSimulation = "Active simulation",
    offlineComputed = "Computed offline from sample triage data",
    severityResult = "Moderate-high risk",
    traumaScoreResult = "GoldenHour trauma score 7/10",
    allocationReason = "MGM selected for Level I readiness and shortest ETA",
    sceneAnalysisResult = "Manual report suggests multi-victim rollover risk",
    protectedTitle = "You are protected.",
    protectedDescription = "The Good Samaritan Law protects bystanders who help road traffic accident victims.",
    treatmentNotice = "Hospitals cannot deny emergency treatment.",
    anonymityNotice = "Helpers can remain anonymous.",
    legalTitle = "No legal liability",
    legalBody = "Good-faith emergency assistance is protected under Good Samaritan provisions.",
    financialTitle = "No financial liability",
    financialBody = "Helpers are not responsible for the victim’s treatment costs.",
    anonymousTitle = "Stay anonymous",
    anonymousBody = "You may choose not to disclose personal details.",
    faqTitle = "Frequently asked questions",
    faqPoliceQuestion = "Can police detain me?",
    faqPoliceAnswer = "No. The law protects Good Samaritans.",
    faqProtectedQuestion = "Am I legally protected?",
    faqProtectedAnswer = "Yes, Good Samaritan protections apply to qualifying assistance.",
    faqIdentityQuestion = "Must I reveal my identity?",
    faqIdentityAnswer = "No. Anonymous assistance is allowed.",
    understandButton = "I Understand — Get Help Now",
    gslProtected = "GSL Protected",
    locationTitle = "Accident location",
    traumaCentreTitle = "Nearest trauma centre",
    distance = "Distance",
    eta = "ETA",
    victimCount = "Number of victims",
    tapAlert = "Tap to alert nearest trauma centre",
    call108 = "Call 108",
    call112 = "Call 112",
    triageTitle = "Quick Triage",
    triageSubtitle = "Three rapid observations for the simulated trauma alert.",
    questionConscious = "Is the victim conscious?",
    questionBleeding = "Visible heavy bleeding?",
    questionBreathing = "Is the victim breathing?",
    yes = "YES",
    no = "NO",
    previous = "Previous",
    voiceReport = "Voice Report",
    tapSpeak = "Tap to Speak",
    simulatedListening = "Simulated listening…",
    describeScene = "Describe the scene",
    scenePlaceholder = "2 victims, one unconscious, car overturned",
    skip = "Skip",
    proceed = "Send simulated alert",
    alertingTitle = "Alerting Trauma Centre...",
    alertingSubtitle = "Running a realistic academic dispatch simulation",
    locationPinged = "Location pinged",
    traumaIdentified = "Trauma centre identified",
    triageSent = "Triage data sent",
    ambulanceDispatched = "Ambulance dispatched",
    corridorActivated = "Green corridor activated",
    hospitalAlerted = "Hospital Alerted",
    ambulanceEta = "Ambulance ETA",
    corridor = "Green Corridor",
    active = "Active",
    liveTracking = "Live Ambulance Tracking",
    currentLocation = "Current location",
    traumaTeamPreparing = "Trauma Team Preparing",
    surgeonAlerted = "Trauma surgeon alerted",
    bloodBank = "Blood bank on standby",
    emergencyBay = "Emergency bay cleared",
    radiology = "Radiology informed",
    theatre = "Operating theatre notified",
    triageReceived = "Triage data received",
    triageSummary = "Triage Summary",
    conscious = "Conscious",
    unconscious = "Unconscious",
    bleeding = "Heavy bleeding",
    noBleeding = "No heavy bleeding",
    breathing = "Breathing",
    notBreathing = "Not breathing",
    notAnswered = "Not answered",
    roadmapTitle = "Future AI Roadmap",
    futureFeature = "Future Feature",
    aiSeverity = "AI Severity Prediction",
    aiScoring = "AI Trauma Scoring",
    aiAllocation = "AI Hospital Allocation",
    aiScene = "AI Accident Scene Analysis",
    restart = "Restart demonstration"
)

private val Hindi = English.copy(
    subtitle = "सड़क दुर्घटना प्रतिक्रिया",
    tagline = "हर सेकंड मायने रखता है।",
    languagePrompt = "अपनी भाषा चुनें",
    continueLabel = "आगे बढ़ें",
    developedBy = "Aadi Shah (CSE Engineer) और Diksha Mohanty (MBBS Student) द्वारा विकसित",
    prototypeNotice = "प्रोटोटाइप संस्करण 1.0 · केवल शैक्षणिक प्रदर्शन",
    simulationBadge = "सिमुलेशन",
    stepAlert = "अलर्ट",
    stepRoute = "मार्ग",
    stepHospital = "अस्पताल",
    sosSimulationNotice = "केवल सिमुलेटेड अलर्ट — कोई डेटा नहीं भेजा जाता।",
    triageSimulationNotice = "केवल शैक्षणिक सिमुलेशन। कोई माइक्रोफोन ऑडियो या अस्पताल अलर्ट नहीं भेजा जाता।",
    simulatedDispatchChecklist = "सिमुलेटेड डिस्पैच चेकलिस्ट",
    academicSafetyNote = "शैक्षणिक सुरक्षा नोट",
    alertingSafetyNotice = "यह ऐप MGM अस्पताल, एम्बुलेंस सेवा, पुलिस या किसी बाहरी बैकएंड से संपर्क नहीं करता। यहाँ दिखाया गया संचार केवल सिमुलेटेड नमूना डेटा है।",
    dashboardSubtitle = "सिमुलेटेड अस्पताल तैयारी डैशबोर्ड",
    greenCorridorActive = "ग्रीन कॉरिडोर सक्रिय",
    speed = "गति",
    destination = "गंतव्य",
    minutesUnit = "मिनट",
    speedUnit = "किमी/घं",
    roadmapDescription = "ऑफलाइन सिमुलेटेड AI मॉड्यूल प्रोटोटाइप प्रदर्शन के लिए सक्रिय हैं। ये डॉक्टर के निर्णय का विकल्प नहीं हैं।",
    liveGpsSimulation = "लाइव GPS सिमुलेशन",
    ambulanceOnWay = "एम्बुलेंस रास्ते में है",
    paramedicUnit = "पैरामेडिक यूनिट GH-12",
    trackingDispatched = "एम्बुलेंस रवाना",
    trackingEnRoute = "कामोठे सेक्टर रोड पार कर रही है",
    trackingNearScene = "NH-66 जंक्शन के पास",
    trackingArriving = "दुर्घटना स्थल पर पहुंच रही है",
    distanceRemaining = "शेष दूरी",
    lastUpdated = "अभी अपडेट हुआ",
    simulatedAiTitle = "सिमुलेटेड AI निर्णय सहायता",
    activeSimulation = "सक्रिय सिमुलेशन",
    offlineComputed = "नमूना ट्राइएज डेटा से ऑफलाइन गणना",
    severityResult = "मध्यम-उच्च जोखिम",
    traumaScoreResult = "GoldenHour ट्रॉमा स्कोर 7/10",
    allocationReason = "Level I तैयारी और सबसे कम ETA के कारण MGM चयनित",
    sceneAnalysisResult = "मैनुअल रिपोर्ट बहु-पीड़ित रोलओवर जोखिम दिखाती है",
    protectedTitle = "आप सुरक्षित हैं।",
    protectedDescription = "गुड समैरिटन कानून सड़क दुर्घटना पीड़ितों की मदद करने वाले लोगों की रक्षा करता है।",
    treatmentNotice = "अस्पताल आपातकालीन उपचार से इनकार नहीं कर सकते।",
    anonymityNotice = "मददगार गुमनाम रह सकते हैं।",
    legalTitle = "कोई कानूनी दायित्व नहीं",
    financialTitle = "कोई वित्तीय दायित्व नहीं",
    anonymousTitle = "गुमनाम रहें",
    faqTitle = "अक्सर पूछे जाने वाले प्रश्न",
    faqPoliceQuestion = "क्या पुलिस मुझे रोक सकती है?",
    faqPoliceAnswer = "नहीं। कानून गुड समैरिटन की रक्षा करता है।",
    faqProtectedQuestion = "क्या मैं कानूनी रूप से सुरक्षित हूँ?",
    faqProtectedAnswer = "हाँ, योग्य सहायता पर गुड समैरिटन संरक्षण लागू होता है।",
    faqIdentityQuestion = "क्या पहचान बताना जरूरी है?",
    faqIdentityAnswer = "नहीं। गुमनाम सहायता की अनुमति है।",
    understandButton = "मैं समझता हूँ — अभी सहायता लें",
    gslProtected = "GSL सुरक्षित",
    locationTitle = "दुर्घटना का स्थान",
    traumaCentreTitle = "निकटतम ट्रॉमा सेंटर",
    distance = "दूरी",
    eta = "आगमन समय",
    victimCount = "पीड़ितों की संख्या",
    tapAlert = "निकटतम ट्रॉमा सेंटर को अलर्ट करने के लिए टैप करें",
    call108 = "108 कॉल करें",
    call112 = "112 कॉल करें",
    triageTitle = "त्वरित ट्राइएज",
    triageSubtitle = "सिमुलेटेड ट्रॉमा अलर्ट के लिए तीन त्वरित निरीक्षण।",
    questionConscious = "क्या पीड़ित होश में है?",
    questionBleeding = "क्या भारी रक्तस्राव दिखाई दे रहा है?",
    questionBreathing = "क्या पीड़ित सांस ले रहा है?",
    yes = "हाँ",
    no = "नहीं",
    previous = "पिछला",
    voiceReport = "वॉइस रिपोर्ट",
    tapSpeak = "बोलने के लिए टैप करें",
    simulatedListening = "सिमुलेटेड सुनना…",
    describeScene = "घटनास्थल का वर्णन करें",
    skip = "छोड़ें",
    proceed = "सिमुलेटेड अलर्ट भेजें",
    alertingTitle = "ट्रॉमा सेंटर को अलर्ट किया जा रहा है...",
    alertingSubtitle = "शैक्षणिक डिस्पैच सिमुलेशन चल रहा है",
    locationPinged = "स्थान पिंग किया गया",
    traumaIdentified = "ट्रॉमा सेंटर पहचाना गया",
    triageSent = "ट्राइएज डेटा भेजा गया",
    ambulanceDispatched = "एम्बुलेंस रवाना की गई",
    corridorActivated = "ग्रीन कॉरिडोर सक्रिय",
    hospitalAlerted = "अस्पताल अलर्ट हुआ",
    ambulanceEta = "एम्बुलेंस आगमन",
    corridor = "ग्रीन कॉरिडोर",
    active = "सक्रिय",
    liveTracking = "लाइव एम्बुलेंस ट्रैकिंग",
    currentLocation = "वर्तमान स्थान",
    traumaTeamPreparing = "ट्रॉमा टीम तैयारी कर रही है",
    triageSummary = "ट्राइएज सारांश",
    roadmapTitle = "भविष्य की AI रूपरेखा",
    futureFeature = "भविष्य की सुविधा",
    restart = "प्रदर्शन फिर शुरू करें"
)

private val Marathi = English.copy(
    subtitle = "रस्ता अपघात प्रतिसाद",
    tagline = "प्रत्येक सेकंद महत्त्वाचा.",
    languagePrompt = "तुमची भाषा निवडा",
    continueLabel = "पुढे जा",
    developedBy = "Aadi Shah (CSE Engineer) आणि Diksha Mohanty (MBBS Student) यांनी विकसित केले",
    prototypeNotice = "प्रोटोटाइप आवृत्ती 1.0 · केवळ शैक्षणिक प्रात्यक्षिक",
    simulationBadge = "सिम्युलेशन",
    stepAlert = "अलर्ट",
    stepRoute = "मार्ग",
    stepHospital = "रुग्णालय",
    sosSimulationNotice = "केवळ सिम्युलेटेड अलर्ट — कोणताही डेटा पाठवला जात नाही.",
    triageSimulationNotice = "केवळ शैक्षणिक सिम्युलेशन. मायक्रोफोन ऑडिओ किंवा रुग्णालय अलर्ट पाठवला जात नाही.",
    simulatedDispatchChecklist = "सिम्युलेटेड डिस्पॅच चेकलिस्ट",
    academicSafetyNote = "शैक्षणिक सुरक्षा नोंद",
    alertingSafetyNotice = "हे ऐप MGM रुग्णालय, रुग्णवाहिका सेवा, पोलीस किंवा कोणत्याही बाह्य बॅकएंडशी संपर्क करत नाही. येथे दाखवलेला संवाद सिम्युलेटेड नमुना डेटा आहे.",
    dashboardSubtitle = "सिम्युलेटेड रुग्णालय तयारी डॅशबोर्ड",
    greenCorridorActive = "ग्रीन कॉरिडोर सक्रिय",
    speed = "वेग",
    destination = "गंतव्य",
    minutesUnit = "मिनिटे",
    speedUnit = "किमी/ता",
    roadmapDescription = "ऑफलाइन सिम्युलेटेड AI मॉड्यूल प्रोटोटाइप प्रात्यक्षिकासाठी सक्रिय आहेत. ते डॉक्टरांच्या निर्णयाचा पर्याय नाहीत.",
    liveGpsSimulation = "लाइव्ह GPS सिम्युलेशन",
    ambulanceOnWay = "रुग्णवाहिका मार्गावर आहे",
    paramedicUnit = "पॅरामेडिक युनिट GH-12",
    trackingDispatched = "रुग्णवाहिका रवाना",
    trackingEnRoute = "कामोठे सेक्टर रस्ते पार करत आहे",
    trackingNearScene = "NH-66 जंक्शनजवळ",
    trackingArriving = "अपघातस्थळी पोहोचत आहे",
    distanceRemaining = "उरलेले अंतर",
    lastUpdated = "आत्ताच अपडेट",
    simulatedAiTitle = "सिम्युलेटेड AI निर्णय सहाय्य",
    activeSimulation = "सक्रिय सिम्युलेशन",
    offlineComputed = "नमुना ट्रायेज डेटावरून ऑफलाइन गणना",
    severityResult = "मध्यम-उच्च धोका",
    traumaScoreResult = "GoldenHour ट्रॉमा स्कोर 7/10",
    allocationReason = "Level I तयारी आणि कमी ETA मुळे MGM निवडले",
    sceneAnalysisResult = "मॅन्युअल रिपोर्ट बहु-पीडित रोलओव्हर धोका दर्शवतो",
    protectedTitle = "तुम्ही सुरक्षित आहात.",
    protectedDescription = "गुड समेरिटन कायदा रस्ता अपघातग्रस्तांना मदत करणाऱ्या व्यक्तींचे संरक्षण करतो.",
    treatmentNotice = "रुग्णालये आपत्कालीन उपचार नाकारू शकत नाहीत.",
    anonymityNotice = "मदत करणारी व्यक्ती अनामिक राहू शकते.",
    legalTitle = "कायदेशीर दायित्व नाही",
    financialTitle = "आर्थिक दायित्व नाही",
    anonymousTitle = "अनामिक रहा",
    faqTitle = "वारंवार विचारले जाणारे प्रश्न",
    faqPoliceQuestion = "पोलीस मला थांबवू शकतात का?",
    faqPoliceAnswer = "नाही. कायदा गुड समेरिटनचे संरक्षण करतो.",
    faqProtectedQuestion = "मला कायदेशीर संरक्षण आहे का?",
    faqProtectedAnswer = "होय, पात्र मदतीवर गुड समेरिटन संरक्षण लागू होते.",
    faqIdentityQuestion = "ओळख सांगणे आवश्यक आहे का?",
    faqIdentityAnswer = "नाही. अनामिक मदतीला परवानगी आहे.",
    understandButton = "मला समजले — आता मदत मिळवा",
    gslProtected = "GSL सुरक्षित",
    locationTitle = "अपघाताचे ठिकाण",
    traumaCentreTitle = "जवळचे ट्रॉमा सेंटर",
    distance = "अंतर",
    eta = "आगमन वेळ",
    victimCount = "पीडितांची संख्या",
    tapAlert = "जवळच्या ट्रॉमा सेंटरला अलर्ट करण्यासाठी टॅप करा",
    call108 = "108 कॉल करा",
    call112 = "112 कॉल करा",
    triageTitle = "त्वरित ट्रायेज",
    triageSubtitle = "सिम्युलेटेड ट्रॉमा अलर्टसाठी तीन जलद निरीक्षणे.",
    questionConscious = "पीडित व्यक्ती शुद्धीवर आहे का?",
    questionBleeding = "तीव्र रक्तस्राव दिसत आहे का?",
    questionBreathing = "पीडित व्यक्ती श्वास घेत आहे का?",
    yes = "होय",
    no = "नाही",
    previous = "मागे",
    voiceReport = "व्हॉइस रिपोर्ट",
    tapSpeak = "बोलण्यासाठी टॅप करा",
    simulatedListening = "सिम्युलेटेड ऐकणे…",
    describeScene = "घटनास्थळाचे वर्णन करा",
    skip = "वगळा",
    proceed = "सिम्युलेटेड अलर्ट पाठवा",
    alertingTitle = "ट्रॉमा सेंटरला अलर्ट करत आहे...",
    alertingSubtitle = "शैक्षणिक डिस्पॅच सिम्युलेशन सुरू आहे",
    locationPinged = "स्थान पिंग केले",
    traumaIdentified = "ट्रॉमा सेंटर ओळखले",
    triageSent = "ट्रायेज डेटा पाठवला",
    ambulanceDispatched = "रुग्णवाहिका रवाना",
    corridorActivated = "ग्रीन कॉरिडोर सक्रिय",
    hospitalAlerted = "रुग्णालय अलर्ट झाले",
    ambulanceEta = "रुग्णवाहिका आगमन",
    corridor = "ग्रीन कॉरिडोर",
    active = "सक्रिय",
    liveTracking = "थेट रुग्णवाहिका ट्रॅकिंग",
    currentLocation = "सध्याचे स्थान",
    traumaTeamPreparing = "ट्रॉमा टीम तयारी करत आहे",
    triageSummary = "ट्रायेज सारांश",
    roadmapTitle = "भविष्यातील AI आराखडा",
    futureFeature = "भविष्यातील सुविधा",
    restart = "प्रात्यक्षिक पुन्हा सुरू करा"
)

fun stringsFor(languageCode: String): AppStrings = when (languageCode) {
    "hi" -> Hindi
    "mr" -> Marathi
    else -> English
}
